import pymysql
from elasticsearch import Elasticsearch

ogging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "B1kpjK9Ry7qtd4B3o37JVBxk"

# Found in the 'Manage Deployment' page
CLOUD_ID = "job_search_es:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJGMyYTNlOGM3ZGNmYTRiOTNhNmU2MzdiZTVlYzE5NmUxJDZkODk0NGNlNGFhODQyYzY4NWNlY2NjNDMwZjBjMTJj"

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)


def get_data():
    conn=pymysql.connect(host="localhost",port=3306,user="root",password="admin",database="freshshop")
    cursor=conn.cursor()
    sql="select * from shop"
    cursor.execute(sql)
    results=cursor.fetchall()
    conn.close()
    return results

def create_es_data():
    es=Elasticsearch()
    try:
        results=get_data()
        for row in results:
            print(row)
            message={
                "id":row[0],
                "name":row[1],
                "shop":row[2],
                "category":row[4],
                "price":row[-1]
            }
            es.index(index="freshshop",doc_type="test-type",body=message)
    except Exception as e:
        print("Error:"+str(e))
if __name__=="__main__":
    create_es_data()